### ISSUE TITLE
Fix Bug:  Differentiate between the Nested and Repeated fields for bigquery when executing datacontract import.

### ISSUE THREAD

**Issue by gregoireAGBG** [datacontract/datacontract-cli#737]
Hello, 
So in version of datacontract-cli 0.10.24 and preivous versions, there is type mismatch in the schema that is being imported from bigquery for **REPEATED RECORD**:

when executing 
`datacontract import --format biquery --biquery-project my_gcp_project --biquery-dataset my_dataset --bigquery-table my_table >> dc_my_gcp_project_my_dataset_my_table.yml `

inside my dc_my_gcp_project_my_dataset_my_table.yml the following will be generated for the my_bq_col (nested : 

`      my_bq_col:
        **type: object
        required: false
        fields**:
          subfield1:
            type: string
            required: true
          subfiel2:
            type: string
            required: false
          subfield3:
            type: string
            required: false`

After adding the server informations, a manual modification is needed in order to be able to execute : 
`datacontract test dc_my_gcp_project_my_dataset_my_table.yml --logs`

the correct adaptation is as follow: 
`      my_bq_col:
        **type: array
        items:
          type: record
          fields:**
            subfield1:
              type: string
              required: true
            subfield2:
              type: string
              required: false
            subfield3:
              type: string
              required: false`

Below you can find the ouput of executing `datacontract test dc_my_gcp_project_my_dataset_my_table.yml --logs`
Before the modification: 
descriptions Check that field my_bq_col has type STRUCT<subfield1 STRING, subfield2 STRING, subfield3 STRING>: Type Mismatch, Expected Type: STRUCT<subfield1 STRING, subfield2 STRING, subfield3 STRING>;
Actual Type: ARRAY<STRUCT<subfield1 STRING, subfield2 STRING, subfield3 STRING>>

After the modification: 

passed │ Check that field my_bq_col has type ARRAY<STRUCT<subfield1 STRING, subfield2 STRING, subfield3 STRING>>│ my_bq_col│         │

Explanation: 
- So currently datacontract-cli **import --format biquery** is handling the nested repeated fields as nested fields : 
Nested fields (or Struct ) are defined by:  type": "RECORD", "mode": "NULLABLE",
while nested repeated fields (or Array<Struct>) are defined by: type": "RECORD", "mode": "REPEATED",
RECORD type seems to be handled as a unique case and not have different behavior depending on the mode.

To resolve the issue you should check the mode of the field and handle the mode "REPEATED" as described above to enable a valid datacontract schema check. 

Best regards.

**Comment by gregoireAGBG** [comment]
Ok i couple notes on how to fix that: 

1) the way to fix nested field issue be replacing if condition at : https://github.com/datacontract/datacontract-cli/blob/main/datacontract/imports/bigquery_importer.py#L138
with
----------------------
        if field.get("type") == "RECORD":
            if field.get("mode") == "REPEATED" :
                imported_fields[field_name].type = "array"
                imported_fields[field_name].items = Field(type="record",fields=import_table_fields(field.get("fields")))
            else :
                imported_fields[field_name].type = "object"
                imported_fields[field_name].fields = import_table_fields(field.get("fields"))

----------------------

2) the JSON type is not handled correctly as well should be fixed to make the datacontract test command work for json object which look like that after executing datacontract import: 
----------------------
        optimization_details:
            type: object
            required: false
----------------------
as this dict does not contain a fields key adding "JSON" as fallback return value.
a)https://github.com/datacontract/datacontract-cli/blob/main/datacontract/export/sql_type_converter.py#L338
is now 
----------------------
    if field_type.lower() in ["object", "record", "struct"]:
        nested_fields = []
        if not field.fields:
            return "JSON"
        for nested_field_name, nested_field in field.fields.items():
            nested_field_type = convert_type_to_bigquery(nested_field)
            nested_fields.append(f"{nested_field_name} {nested_field_type}")

----------------------

3) seems that the type ARRAY<STRING> and ARRAY<INTEGER> are not currently supported by datacontract-cli 
i have a double nested element: ARRAY<STRUCT<... , steps ARRAY<STRUCT< kind STRING,substeps ARRAY<STRING>>>>>
----------------------
            steps:
              type: array
              required: false
              items:
                type: record
                fields:
                  kind:
                    type: string
                    required: false
                  substeps:
                    type: string
                    required: false
----------------------
substeps is  type: STRING mode: REPEATED (thus the ARRAY<STRING>)
this information is lost when importing using datacontract import , and thus when doing the datacontract test command the check schema is : ARRAY<STRUCT<... , steps ARRAY<STRUCT< kind STRING,**substeps STRING**>>>> instead of ARRAY<STRUCT<... , steps ARRAY<STRUCT< kind STRING,substeps **ARRAY<STRING>**>>>>
Same for INTEGER fields meaning (ARRAY<INTEGER>)

Best regards.

**Comment by jochenchrist** [comment]
Thanks for opening this issue! Would you be open to contributing a pull request for this? We’d be happy to support you through the process if needed.

**Comment by codeagent-art** [comment]
Hello yes i can do the pull request ( i have it locally but am not allowed to push to the repository) can you add me as a contributor? 
Btw this is original author (gregoireAGBG ) had some issue with the other account.

**Comment by codeagent-art** [comment]
Hello @jochenchrist could you grant me contributor access ? 
still getting access denied on the repository. 
We would like to integrate the fix inside your repository so that we could use it in production. 
`❯ git push --set-upstream origin fix/Issue_737
ERROR: Permission to datacontract/datacontract-cli.git denied to codeagent-art.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~/Develop/Source/github/datacontract-cli fix/Issue_737 ❯ `

Kind regards. Gregoire.

**Comment by jochenchrist** [comment]
Please create a fork to your Github Account, then you can create a Pull Request.
Direct Repo Access is for Maintainers, only.

**Comment by gregoire-lab** [comment]
Hello any update on this ? we will be deploying on central orchestrator soon and would be nice to know what should be fixed in the Pull Request (beside rebasing to latest version). 
For context the fork based on 0.10.24 is handling the nested fields and complex schema properly.
Cheers Gregoire.
